version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout

      # generate and build project to test
      - run: .circleci/test-setup.sh

      # run tests
      - run: .circleci/test-run.sh
